# 开发环境配置
paths:
  # 开发环境源视频目录
  source_dir: C:\Users\watermelon\Downloads\test
  # 开发环境字幕输出目录
  target_dir: C:\Users\watermelon\Downloads\test\data
  cache_dir: C:\Users\watermelon\Downloads\test\.cache